name = "SummaryTree"
uuid = "d5c4171b-6993-4d1f-b0c8-7d5c65988a1e"
authors = ["Alfred Wong <alfred.cl.wong@gmail.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
AbstractTrees = "0.3"
julia = "1.6"
